version: '3'
services:

  chrome:
    container_name: chrome
    hostname: chrome
    image: alekzonder/puppeteer:latest
    volumes:
      - ./index.js:/app/index.js:ro
    entrypoint:
      - node
      - /app/index.js
    environment:
      - PUREGYM_EMAIL
      - PUREGYM_PIN

#  website:
#    container_name: website
#    hostname: website
#    build: .
#    ports:
#      - "5000:5000"
